[project]
name = "tinyrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tinytune>=0.0.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
